### ISSUE TITLE
Missing the framework's version

### ISSUE THREAD

**Issue by styfle** [webcomponents/custom-elements-everywhere#2]
This is really cool! Thanks for the detailed write ups!

---------

That being said...

I would expect to see which version of React was tested in the [test results](https://custom-elements-everywhere.com/libraries/react/results/results.html).

For example, **React 15.6.1**

Otherwise the results will become stale and no one will know.

**Comment by rbvea** [comment]
Likewise, it'd be best to have it say Angular 2, I'd be interested in pulling in Angular 1 as well, since I'm sure there are lots of legacy Angular 1 apps that would benefit from having Custom Element interop.

**Comment by robdodson** [comment]
Good call on adding the version numbers. I'll work on that.

Regarding Angular.js (a.k.a. Angular 1.x) I thought about adding it. The problem is any issues are not likely to be fixed. The Angular team, to my knowledge, is no longer working on 1.x. So whatever score Angular.js gets will be low and stay that way.

Having said that, I've seen a number of folks request Angular.js so it might be worthwhile to add it anyway and just explain in the summary that the score is unlikely to improve. If there are any Angular.js experts who would be interested in doing a PR to get things started I would ❤️ them :)
