### ISSUE TITLE
Cover Salesforce "Lightning Web Components"

### ISSUE THREAD

**Issue by rtm** [webcomponents/custom-elements-everywhere#479]
It would be great to cover Saleforce "Lightning Web Components", which are claimed to be based on web standards but in practice completely fail all interoperability criteria, if for no other reason than to shame Salesforce.

**Comment by caridy** [comment]
@rtm we will send a PR at some point in the future, but this repo does not have any framework that is not yet open sourced. If you are interested, I can add you to a couple of repos where you can try our experimental APIs.

There are two folds to the interop with WC: 
a) a framework that supports using any WC (this is what this repo covers)
b) a framework that produces good WC (and how good are those components, this is more difficult to assess)

I suspect that you have played around with Lightning Web Components inside the Salesforce's Lightning Platform, which has a lot more restrictions in place (due to Locker Service). If you want to try LWC in stand alone mode, just like any framework tested by this repo, just let me know, and I can add you to a couple of repos, maybe you will see the difference.

As for your last statement, I don't think custom-elements-everywhere charter is to shame people or projects, it is to make them better, to help them be more interoperable, and that takes time and effort. For LWC, it is very very early on.

**Comment by rtm** [comment]
@caridy Thanks for your response. I have played with LWC's outside of the Salesforce environment using the `@lwc/compiler` package and tested them using `@salesforce/lwc-jest`. Please do provide any other information about how to play with thim in stand-alone mode, that would be much appreciated.

**Comment by caridy** [comment]
Ah, that explains! jest uses jsdom, which does [not support web components API atm](https://github.com/jsdom/jsdom/issues/1030) (we have multiple PRs open for jsdom to get this done). Since this is not the right place to follow up, expect an invitation for a private repo in a couple of days, and we can continue the discussion there.

**Comment by robdodson** [comment]
Looks like y'all have got things sorted so I'm going to close this issue if that's ok.

**Comment by tbranyen** [comment]
Just as a heads up a formal PR has been opened in JSDOM to land WC support: https://github.com/jsdom/jsdom/pull/2548
