### ISSUE TITLE
Add ef.js

### ISSUE THREAD

**Issue by ClassicOldSong** [webcomponents/custom-elements-everywhere#823]
ef.js is an intuitive framework that works perfectly with custom elements.

- [Repo](https://github.com/TheNeuronProject/ef.js)
- [Website](https://ef.js.org)

**Comment by rictic** [comment]
As the page is currently organized, we need to keep the list to more widely used libraries, otherwise the info that people are most likely coming to see will become steadily harder and harder to find. I'd like to add better filtering and sorting at some point, but for the moment we're looking for some rough gage that libraries have at least moderately wide usage.

I know this is a discouraging message to receive, and I'm sorry about that. When your library is used a bit more widely (or if you have metrics you can point at about usage that I may have missed!) please do resubmit!
